export { createDocumentDBRouter, DocumentDBRouter, defineRoute } from './DocumentDBRouter.js';
export type {
  DocumentDBChangeEvent,
  DocumentDBDeleteRequest,
  DocumentDBDeleteRouteDefinition,
  DocumentDBEvent,
  DocumentDBEventEntry,
  DocumentDBFilterInput,
  DocumentDBFullDocumentBeforeChangeOption,
  DocumentDBFullDocumentOption,
  DocumentDBInsertRequest,
  DocumentDBInsertRouteDefinition,
  DocumentDBMiddleware,
  DocumentDBOperationType,
  DocumentDBReplaceRequest,
  DocumentDBReplaceRouteDefinition,
  DocumentDBRequest,
  DocumentDBResponse,
  DocumentDBRouteDefinition,
  DocumentDBRouterOptions,
  DocumentDBUpdateDescription,
  DocumentDBUpdateRequest,
  DocumentDBUpdateRouteDefinition,
} from './types.js';
